name: 05 Deploy CHR to Azure (05_Deploy_CHR.yml)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load parameters from deploy-params.json
        id: params
        run: |
          jq -r 'to_entries[] | "\(.key)=\(.value)"' deploy-params.json >> $GITHUB_ENV

      - name: Output all deployment parameters from ENV
        run: |
          echo "Loaded deployment environment variables:"
          env | grep -E '^(LOCATION|RESOURCE_GROUP|STORAGE_ACCOUNT|CONTAINER_NAME|VHD_NAME|SP_NAME|PROJECT|ENVIRONMENT|AZ_REGION|CONTAINER_NAME_TF|VNET_NAME|SUBNET_NAME|AZURERM_IMAGE_NAME|AZURERM_NIC_NAME|IP_CONFIGURATION_NAME|AZURERM_VM_NAME|STORAGE_OS_DISK_NAME|STORAGE_OS_DISK_TYPE|AZURERM_ROUTE_TABLE_NAME|AZURERM_VM_SIZE|MIKROTIK_IP|MIKROTIK_USER|MIKROTIK_PASSWORD|INTERFACE_NAME|ADDRESS_LIST_NAME|ADDRESS_LIST_ADDRESS)='

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ADMIN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
