name: 05 Deploy MikroTik CHR to Azure (05_Deploy_CHR.yml)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load parameters from deploy-params.json
        id: params
        run: |
          PARAMS=$(cat deploy-params.json)
          echo "LOCATION=$(echo $PARAMS | jq -r .location)" >> $GITHUB_ENV
          echo "RESOURCE_GROUP=$(echo $PARAMS | jq -r .resource_group)" >> $GITHUB_ENV
          echo "STORAGE_ACCOUNT=$(echo $PARAMS | jq -r .storage_account)" >> $GITHUB_ENV
          echo "CONTAINER_NAME=$(echo $PARAMS | jq -r .container_name)" >> $GITHUB_ENV
          echo "VHD_NAME=$(echo $PARAMS | jq -r .vhd_name)" >> $GITHUB_ENV
          echo "SP_NAME=$(echo $PARAMS | jq -r .sp_name)" >> $GITHUB_ENV

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ADMIN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.2

      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan \
            -var "location=${{ env.LOCATION }}" \
            -var "resource_group=${{ env.RESOURCE_GROUP }}" \
            -var "storage_account=${{ env.STORAGE_ACCOUNT }}" \
            -var "container_name=${{ env.CONTAINER_NAME }}" \
            -var "vhd_name=${{ env.VHD_NAME }}" \
            -var "sp_name=${{ env.SP_NAME }}"

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var "location=${{ env.LOCATION }}" \
            -var "resource_group=${{ env.RESOURCE_GROUP }}" \
            -var "storage_account=${{ env.STORAGE_ACCOUNT }}" \
            -var "container_name=${{ env.CONTAINER_NAME }}" \
            -var "vhd_name=${{ env.VHD_NAME }}" \
            -var "sp_name=${{ env.SP_NAME }}"
