name: 05A Plan Deploy CHR (05A_Plan_Deploy_CHR.yml)

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load parameters from deploy-params.json
        id: params
        run: |
          jq -r 'to_entries[] | "\(.key)=\(.value)"' deploy-params.json >> $GITHUB_ENV

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ADMIN }}

      - name: Extract SP clientId from GitHub secret
        run: echo "SP_APP_ID=$(echo '${{ secrets.AZURE_CREDENTIALS_ADMIN }}' | jq -r .clientId)" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.2

      - name: Terraform Init
        working-directory: terraform/azure
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS_ADMIN).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS_ADMIN).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS_ADMIN).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS_ADMIN).tenantId }}
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/azure
        env:
          ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS_ADMIN).clientId }}
          ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS_ADMIN).clientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS_ADMIN).subscriptionId }}
          ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS_ADMIN).tenantId }}
        run: |
          terraform plan -out=plan.out
          terraform show -json plan.out > plan.json

      - name: Upload Terraform Plan JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: chr-plan-json
          path: terraform/azure/plan.json
          retention-days: 5

      - name: Print Rover usage hint
        run: |
          echo "To visualize the Terraform plan using Rover, download the plan.json artifact and run:"
          echo ""
          echo "docker run --rm -it -p 9000:9000 -v \$(pwd)/plan.json:/src/plan.json im2nguyen/rover:latest -planJSONPath=plan.json"
